<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select colour icon</name>
   <tag></tag>
   <elementGuidId>859b5bf2-b9c4-4cdb-be5d-ee0f13d6a044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chooseColor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chooseColor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91a2db79-dbf2-49ba-a4bb-19b8b7e132d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tool-icon</value>
      <webElementGuid>1f64fcfb-df23-4178-bb5e-efa9a1d655ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>47eb5e94-3809-449e-bedf-3ac490a46f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseColor</value>
      <webElementGuid>16a93475-6f2b-4c1d-883f-f08c3ec335f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>#1913B0</value>
      <webElementGuid>9d1bc0d9-e44c-44ed-a089-692e1441bd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseColor&quot;)</value>
      <webElementGuid>ed9d47a3-ee19-47f9-94d0-628043605c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chooseColor']</value>
      <webElementGuid>3910f1dc-4ad3-4012-85ed-ca700ba4fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='settings']/li/input</value>
      <webElementGuid>ed6fb890-6625-40b3-889c-c7284ecee532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>78e2f8db-a8a7-47b8-bf6c-5a21e80c8f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'color' and @id = 'chooseColor']</value>
      <webElementGuid>6cba206b-de54-4282-972d-2b49ce22e425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
