<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Board name_input field</name>
   <tag></tag>
   <elementGuidId>d2c6d5e0-0536-4aca-8551-88e15907649a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#board</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='board']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eb8b5c4-0d72-4f97-b435-5a144241e9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbff1b18-118b-4f9a-992b-e215acc319b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>board</value>
      <webElementGuid>20eba74f-88d5-4eb2-b6c3-62cb774b2914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>board</value>
      <webElementGuid>60d1977a-476a-4c16-a4bf-bf3563027721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name of the board…</value>
      <webElementGuid>e7769c32-4092-4843-bc93-aab1e7fcc7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board&quot;)</value>
      <webElementGuid>3ff46bd9-6d6e-4a39-b244-9e2611d4844b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='board']</value>
      <webElementGuid>fac28421-ef34-45df-a737-b64ceb860b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='named-board-form']/input</value>
      <webElementGuid>c22bb68a-dd1f-4edf-9f4b-b2673672b5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9f23005c-7bab-4bc0-9a96-9160e6e842ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'board' and @name = 'board' and @placeholder = 'Name of the board…']</value>
      <webElementGuid>968f0f5c-3a3a-4eaa-bdb5-022446018faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
