<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Blue color_option</name>
   <tag></tag>
   <elementGuidId>86cb6804-ea18-4b34-9838-c48d3c0a528f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='color_7FDBFF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#color_7FDBFF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39698e1b-d7d9-44f5-8c4a-fc36f0326ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>colorPresetButton</value>
      <webElementGuid>2d0a4c92-26b0-460f-b682-42fdd0360268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color_7FDBFF</value>
      <webElementGuid>fb5610ee-d49d-49a0-964d-3302a78620dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>keyboard shortcut: 9</value>
      <webElementGuid>74d32377-2a95-46de-922b-1d599937ea99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color_7FDBFF&quot;)</value>
      <webElementGuid>97825e85-9456-4f4c-9955-2839a1526adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='color_7FDBFF']</value>
      <webElementGuid>b02f6af7-01eb-4ad1-96ee-1005cf8f0e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='colorPresetSel']/span[9]</value>
      <webElementGuid>41607c6f-f361-4229-8cc9-90d4ea382473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[9]</value>
      <webElementGuid>ae757f51-4ea8-432c-8810-26894484b5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'color_7FDBFF' and @title = 'keyboard shortcut: 9']</value>
      <webElementGuid>7ca2f25b-dfab-44e2-a9fc-710cb35b0850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
