<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_input field</name>
   <tag></tag>
   <elementGuidId>4e8463ad-6ab7-44b8-bd98-cc3317ce3fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textToolInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textToolInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcf81b4c-210b-4756-b046-1267743629b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textToolInput</value>
      <webElementGuid>d4f47967-84e6-46f4-81f3-af02ce98c626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c2efd96-e3a8-47fa-a3c1-2a179aa51fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c49c0e3-83e7-42b9-9cca-2c084488e6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textToolInput&quot;)</value>
      <webElementGuid>207d078e-77b9-4700-86ea-4cf067f805c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textToolInput']</value>
      <webElementGuid>1258e15f-9b27-4100-a44d-e550e32e20fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='board']/input</value>
      <webElementGuid>6161bf87-f5f3-4be8-bced-4c5627468688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>65154ad2-51fb-4250-ab99-f47fbb5b3179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textToolInput' and @type = 'text']</value>
      <webElementGuid>72dd2cb8-a8e4-4438-8ae4-d33ef31056ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
